In [4]:
import numpy as np

In [19]:
arr = np.ones((3,3),dtype = bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
arr = np.arange(1,10).reshape(3,3)

Mask = arr %2==1
arr[Mask]

array([1, 3, 5, 7, 9])

In [24]:
arr[Mask]= -1
arr[Mask]

array([-1, -1, -1, -1, -1])

In [38]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr2[:,::-1]

array([[3, 2, 1],
       [6, 5, 4]])

In [63]:
arr3 = np.arange(1,10).reshape(3,3)
arr3 =np.where(arr3>5)
arr3 

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [78]:
arr4 = np.arange(1,10).reshape(3,3)
arr4[-1:,-1:]

array([[9]])

In [80]:
normalized = np.array((arr4 - arr4.min())/(arr4.max() - arr4.min()))
print(normalized)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [84]:
arr5 = np.ones((5,5), dtype=int)
arr5[1:-1,1:-1] = 0
arr5

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [88]:
arr6 = np.random.randint((10,10))
arr6
minv = arr6.min()
maxv = arr6.max()
meanv = arr6.mean()
stdv = arr6.std()
print(minv,maxv,meanv,stdv)


2 8 5.0 3.0


In [100]:
arr1 = np.arange(1,3)
arr2 = np.arange(1,5).reshape(2,2)
arr1+arr2

array([[2, 4],
       [4, 6]])

In [110]:
arr6 = np.arange(1,7).reshape(2,3)
result = arr6[arr6[:,0].argsort()]
result


array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
arr01 = np.arange(1,7)
arr02 = np.arange(3,9)

result = np.intersect1d(arr01,arr02)
result

array([3, 4, 5, 6])

In [117]:
arr03 = np.arange(1,7).reshape(2,3)
meanq = arr03.mean(axis=1,keepdims=True)
subv = arr03-meanq
subv


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [ ]:
arr44 = np.arange(1,17).reshape(4,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])